### ISSUE TITLE
Step doesn't respect min/max values

### ISSUE THREAD

**Issue by reintroducing** [tajo/react-range#38]
You can duplicate this in the `BigSteps` example. Set `MIN = 3`, `MAX = 103`, and in the state, set `values: [53]`. The slider handle will render at 53 but the first drag right will go to 60, refresh and first drag left goes to 40. 

What I'd expect to happen in this scenario is that each step would go by values of 10 from the starting value and respect the min/max, so right would be 63, 73, and so on, while left would be 43, 33, and so on.

It would also be good to add clamping to the values. For instance, if my min/max is 10/30 respectively, and my value is 5, it should default to 10. If its 40, it should default to 30. Here is what I've started to implement to get around this (in a wrapper I'm writing for this component), but now that I can't get the step to respect min/max values when dragging I'm stuck.

In my component I set the values that I'll pass to `Range` first:
```js
const [values, setValues] = useState(() =>
    validateValues({defaultValues, min, max, step})
);
```

The above runs this:
```js
// guard against any values that may be outside of the specified min/max range and make sure step aligns
function validateValues({defaultValues, min, max, step}) {
    const totalSteps = Math.floor((max - min) / step);

    return defaultValues.map(val => {
        const steps = Math.min((val - min) / step, totalSteps);
        const newVal = Math.round(steps) * step + min;

        // ensure value is in min/max range
        return clamp(newVal, min, max);
    });
}
```

I'm using lodash clamp for brevity here because its already in my project but you can just as easily run a manual check and set the value accordingly. In the scenario of passing this as props `defaultValues={[41]} step={10} min={3} max={53}` my handle would render at 43 as it should. This gets you almost all the way to success, but the internals of why step is not respected vs min/max is a mystery to me.

**Comment by reintroducing** [comment]
@tajo any update on this by any chance? Does what I described make sense?

**Comment by tajo** [comment]
Yea, just don't have time to look into it right now. Could you try to write a failing test? That would help too!

**Comment by reintroducing** [comment]
@tajo Apologies this took so long, I was on PTO towards the end of last week. Anyway, here is the PR with the requested failing test(s). Let me know if anything else is necessary: https://github.com/tajo/react-range/pull/44

**Comment by gergelyke** [comment]
@reintroducing just took a deeper look into this issue - it was fixed here: https://github.com/tajo/react-range/commit/5147048c3aa6eb1d1ddfd7158d7cf5369736fc49#diff-d4a4a082de6e0c29ee550865b3de8977R17

the reason your test is failing is that there is a syntax error in it: https://travis-ci.org/tajo/react-range/builds/622287473#L205

can you please verify that it works on the latest version?

**Comment by reintroducing** [comment]
@gergelyke Sorry about that, not sure how I didn't catch it. I went ahead and fixed the syntax error however the test is still failing. It doesn't seem like the step is being adjusted properly.

**Comment by gergelyke** [comment]
@reintroducing if you change the value here to `53`, it should work properly: https://github.com/tajo/react-range/pull/44/files#diff-b27a87265cfdf0c4bd3ee2ecc1a366ddR10

**Comment by reintroducing** [comment]
@gergelyke I think I was expecting it to be updated by the library like you mentioned. Its possible that a user would provide an improper step value, or it would creep up somehow, and it should be adjusted accordingly based on step + range. I think my original thought process here was based on how https://github.com/react-component/slider handles it, which I believe it does update it accordingly. If you think this is out of scope, I can certainly make that change, but I think it would be a nice addition.

**Comment by gergelyke** [comment]
yeah, that makes sense too

@tajo what do you think?

**Comment by tajo** [comment]
Yea, I think we should solve it in our library since the native [input range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) is also auto-correcting the value (it moves the thumb to the closest valid value). I've been trying to mimic the native behavior as much as possible so far.

**Comment by gergelyke** [comment]
sounds good - I'll open a PR later today

**Comment by reintroducing** [comment]
fantastic, thanks guys! Really appreciate all the work being put into this.

**Comment by gergelyke** [comment]
we've chatted more about this with @tajo offline, and decided to go with this approach: https://github.com/tajo/react-range/pull/58

the reason for this is that if an incorrect initial state is provided we'd have to fix that by calling the `onChange` prop, or display incorrect data

**Comment by reintroducing** [comment]
fair enough. thank you.
